apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: team1
spec:
  encryptedData:
    foo: AgB0GfkOvTE7dPSRjHJeiH5XqHK2+QDhqzMfQSN10Wa7SbRF0rXCSGOqDevAQ5Vqewxbr9UcyDssb5r+u+5ee+HaxQXvLPmU2oTVVvcqOytfY4v1ibWN1INCVJxCUTFFYEZyU7ZbadPuyXpn9pyWsdOkBqRfzaJh+gPO3z8MPhnTsMFfMY5/ZLaM4nS4tLqb4x+70wvFUBkmYDxgxd07FDgffAFlRqyUSV96xVGLFMgO/0qO2YebgiK/FnXaAoCXVJGunovLOEJ4Sk9MCabVEkQrBHARlWUtsrbj3xMcf2DnP+sgbc3h2ZPVnTlD43puUxak3/Dro8DHVgIi+85C/EBPLIyS1VYezADFCVThMYDwCP7KFt7CUnhOEXaSLWcLSIGw0HFB/8Sjx834Dmr2dVVk0hpKWFGiqmVDhRNa37d1YG6jlByONR2kcpTWGry1reR3SSdcLAoQgF6vM882fwFWW0qL0pVL7VWJO9LKCFBzdZdujpI+I53lbtGxx7fqHyzfX+K1GufzL5IXMjBjT4SW12A0O2hV7oh0Q3Y8FxRQTjgXzQ9whXn37O8hENvAdTi4WacO2ADEPrGDj5MAj0BPGOv5zjCfJK4OIVc/++xl66ArCeRakEfJYesqofCFDB8pjHtmGiPHL0/uVFB+KFnybxeeXiV7zKIPu5KQCBKoF8qjGg/YCcIADP4q+KvkJRt8wVLW3GC6w+DcG3MgbX3k8dw=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: team1
status: {}

