apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: team1
spec:
  encryptedData:
    foo: AgB0GfkOvTE7dPSRjHJeiH5XqHK2+QDhqzMfQSN10Wa7SbRF0rXCSGOqDevAQ5Vqewxbr9UcyDssb5r+u+5ee+HaxQXvLPmU2oTVVvcqOytfY4v1ibWN1INCVJxCUTFFYEZyU7ZbadPuyXpn9pyWsdOkBqRfzaJh+gPO3z8MPhnTsMFfMY5/ZLaM4nS4tLqb4x+70wvFUBkmYDxgxd07FDgffAFlRqyUSV96xVGLFMgO/0qO2YebgiK/FnXaAoCXVJGunovLOEJ4Sk9MCabVEkQrBHARlWUtsrbj3xMcf2DnP+sgbc3h2ZPVnTlD43puUxak3/Dro8DHVgIi+85C/EBPLIyS1VYezADFCVThMYDwCP7KFt7CUnhOEXaSLWcLSIGw0HFB/8Sjx834Dmr2dVVk0hpKWFGiqmVDhRNa37d1YG6jlByONR2kcpTWGry1reR3SSdcLAoQgF6vM882fwFWW0qL0pVL7VWJO9LKCFBzdZdujpI+I53lbtGxx7fqHyzfX+K1GufzL5IXMjBjT4SW12A0O2hV7oh0Q3Y8FxRQTjgXzQ9whXn37O8hENvAdTi4WacO2ADEPrGDj5MAj0BPGOv5zjCfJK4OIVc/++xl66ArCeRakEfJYesqofCFDB8pjHtmGiPHL0/uVFB+KFnybxeeXiV7zKIPu5KQCBKoF8qjGg/YCcIADP4q+KvkJRt8wVLW3GC6w+DcG3MgbX3k8dw=
    foo2: AgAJfKOTf24Gk5e5BgZhXsU5/YvtZvwpQLHnNfAEEKIo+DsgyCaHaf2Rp50/Dh69od31JBBRk4/eBJ31ok8HztU3IG6DxZ1jrXMfLRr0euT8rMHVUI1DMA5cd/4Es+CNZ6O5OXg3F1zW8vL35yQWCMWuSDk7lKn5CBNRdQdSbZtd4SukOr2sl0fT0C3wXxmT3Imb8Gv6BQhrH1giri56KKYf5KiCfyB74qdZd1qPi/nRb6QodC8rX786hsayMOa83pCXMScU0qhTA9w+lJfOMt6Xt5yB5/px3zQYl0EWXxvwcc8jm5AMbaIva6vuDa0HH5f5jNY1S7zQrwXUxuKIZY+9wsPZknnK13TuuRS8MrkfNiq0YgX4gP5jJrAmZzTqrHstTZ5YHEMz8SagosntA6lTmlzdlUTuAzYK3sgQNA+Q8XdrbHvstEA8Dctnv/5RHsXUyU7XijCGOi4XfJaAvbBV2VwzfhjaYj0SUPnkvaY6HrH7rhLZQug7vZ/fva6Vzazea+p0s+4bbpcNVHzZ6/bVzO9LKBNXI1QoenZ1KeCbV3RUuSw88Jmco4yrWZ8sibeQ47bxSR8lG2EBShrmbkk/MyfNRbcEHSsoF2zECYemlzVXM13xMIia6TBpi33Qw2GCwEgQZ3E6HDnquGtAhk9FAi5MabtJYM1cZH6cwwoCgIUDEgCUBuTUPfcpPDbqhq+XaivAs0TCuJ2qVw05tw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: team1
status: {}

